
/*
* 所有全局变量进行统一管理，大写
* */
export const SHOW_DEL_BUTTON = 'SHOW_DEL_BUTTON'

export const SHOW_EDIT_BUTTON = 'SHOW_EDIT_BUTTON'

export const SET_TABLE_URL = 'SET_TABLE_URL'

export const SET_TABLE_DATA = 'SET_TABLE_DATA'

export const GET_TABLE_DATA = 'GET_TABLE_DATA'

export const SET_TOKEN_DATA = 'SET_TOKEN_DATA'

export const SET_BUTTON_PERMISSION = 'SET_BUTTON_PERMISSION'

export const SET_SYSTEM_PERMISSION = 'SET_SYSTEM_PERMISSION'

export const SET_ASIDETITLE_PERMISSION = 'SET_ASIDETITLE_PERMISSION'

export const SET_ALL_PERMISSION = 'SET_ALL_PERMISSION'

export const SET_TREE_IDS = 'SET_TREE_IDS'

export const SET_SURE_URL =  'SET_SURE_URL'

export const SET_TABLE_TOTAL = 'SET_TABLE_TOTAL'

export const SET_USER_ROUTES = 'SET_USER_ROUTES'
